language : cpp
compiler:
  - g++
before_install:
  - echo $LANG
  - echo $LC_ALL
install:
    # SDL2
    - curl -O http://www.libsdl.org/release/SDL2-2.0.0.zip
    - unzip SDL2-2.0.0.zip
    - (cd SDL2-2.0.0 && ./configure && make && sudo make install)
    - cd ..
    - curl -O http://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.0.zip
    - unzip SDL2_mixer-2.0.0.zip
    - (cd SDL2_mixer-2.0.0 && ./configure && make && sudo make install)
    - cd ..
    - curl -O http://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.0.zip
    - unzip SDL2_image-2.0.0.zip
    - (cd SDL2_image-2.0.0 && ./configure && make && sudo make install)
    - curl -O http://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.12.zip
    - unzip SDL2_ttf-2.0.12.zip
    - (cd SDL2_ttf-2.0.12 && ./configure && make && sudo make install)
    - cd ..
    - pwd
before_script: cd /home/travis/build/richerarc/Projet-SIM/sources/
script: make && make test
branches:
  only:
    - master
notifications:
  recipients:
    - richer.arc@gmail.com
  email:
    on_success: change
    on_failure: change
    on_errored: change
os:
  - linux
env:

addons:
  coverity_scan:
    project:
      name: "richerarc/Projet-SIIM"
      description: "Build submitted via Travis CI"
    notification_email: richer.arc@gmail.com
    build_command_prepend: "make clean"
    build_command:   "make"
    branch_pattern: master
